require('mustafa.packer')
require('mustafa.remap')
require('mustafa.telescope')
require('mustafa.tree-sitter')
require('mustafa.mason-lsp')
require('mustafa.rose')
require('mustafa.cmp')
require('mustafa.dap')
