require('plugins.harpoon')
require('plugins.remap')
require('plugins.telescope')
require('plugins.mason-lsp')
require('plugins.cmp')
require('plugins.theme')
require('plugins.lualine')
require('nvim-ts-autotag').setup()
